@ShopApp_HostAddress = http://localhost:5157

GET {{ShopApp_HostAddress}}/api/product
Accept: application/json

GET {{ShopApp_HostAddress}}/api/product/1
Accept: application/json

GET {{ShopApp_HostAddress}}/api/category
Accept: application/json