POST https://localhost:7100/api/user/register
Content-Type: application/json

{
  "id": 1,
  "login": "admin",
  "hashPassword": "123",
  "email": "admin@test.com"
}

###

POST https://localhost:7100/api/user/register
Content-Type: application/json

{
  "id": 2,
  "login": "user",
  "hashPassword": "123",
  "email": "user@test.com"
}